### ISSUE TITLE
Displaying all errors in production?

### ISSUE THREAD

**Issue by RickWieman** [WISVCH/wisv.ch#1]
Are you sure you want these lines in production code (e.g. `redirect.php`)?

``` php
error_reporting(E_ALL);
ini_set("display_errors", 1);
```

**Comment by jabbink** [comment]
![](http://gifs.joelglovier.com/no/old-man-no.gif)

**Comment by sanderploegsma** [comment]
Waarom watch ik niet automatisch mijn eigen repo github? 

![](http://gifs.joelglovier.com/facepalm/picard-facepalm-o.gif)

**Comment by sanderploegsma** [comment]
Anyway, @RickWieman, daar heb je wel een goed punt.

**Comment by RickWieman** [comment]
Top! Je hebt trouwens wel `admin/ajax.php` gemist @sanderploegsma :stuck_out_tongue_winking_eye:

**Comment by sanderploegsma** [comment]
Ja, haast en zo :')

On Thursday, April 23, 2015, Rick Wieman notifications@github.com wrote:

> Top! Je hebt trouwens wel admin/ajax.php gemist @sanderploegsma
> https://github.com/sanderploegsma [image:
> :stuck_out_tongue_winking_eye:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WISVCH/wisv.ch/issues/1#issuecomment-95485418.

## 

_Sander Ploegsma_
Commissaris Public Relations
der W.I.S.V. 'Christiaan Huygens'

## 

t: +31 15 278 2532
e: cpr@ch.tudelft.nl
w: http://ch.tudelft.nl
